<?php
/**
 * Implements hook_permission().
 */
function omitsis_SITEID_config_permission(){
  return array(
    'administer omitsis pbwc settings' => array(
      'title' => t('Administer Omitsis PBWC settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function omitsis_SITEID_config_menu() {
  $items = array();

  $items['admin/config/services/config'] = array(
    'title' => 'PBWC Configuration',
    'description' => 'Change parameters for this site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('omitsis_SITEID_config_settings'),
    'access arguments' => array('administer omitsis pbwc settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: Current posts settings
 *
 * @see omitsis_SITEID_config_menu()
 */
function omitsis_SITEID_config_settings($form, &$form_state) {
  $form = array();

  // CRAWL
  /*$form['crawl'] = array(
    '#type' => 'fieldset',
    '#title' => t("Crawl"),
    '#description' => t("Shows an urgent message crawling from right to left"),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['crawl']['crawl_active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Activate'),
    '#default_value' => variable_get('omitsis_weloba_config_crawl_active'),
    '#description' => t("Check to show the crawl with the message, uncheck to hide it"),
  );*/

  $form['#submit'][] = 'omitsis_SITEID_config_settings_form_submit';

  return system_settings_form($form);
}

/**
 * Implements validation from the Form API.
 *
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state
 *   during processing.
 */
function omitsis_SITEID_config_settings_validate($form, &$form_state){
  
}

/**
 * Implements submission from the Form API.
 *
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state
 *   during processing.
 */
function omitsis_SITEID_config_settings_form_submit($form, &$form_state) {
  // CRAWL
  /*variable_set('omitsis_weloba_config_crawl_active', $form_state['values']['crawl_active']);*/
}
