<?php
define('SITE_ID', 'SITEID');
define('CURRENT_MODULE_PATH', drupal_get_path('module', SITE_ID));

/**
 * Implements hook_menu().
 */
function omitsis_SITEID_menu() {
  $items = array();

  $items['oasync/test/%'] = array(
    'page callback' => 'omitsis_SITEID_test',
    'type' => MENU_CALLBACK,
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 *  Implementation of hook_page_alter().
 */
function omitsis_SITEID_page_alter(&$page) {

}

/**
 *  Implementation of hook_form_validate().
 */
function omitsis_SITEID_form_validate($form, &$form_state) {

}

/**
 *  Implementation of hook_form_alter().
 */
function omitsis_SITEID_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'comment_form':
      $form['comment_body']['#after_build'][] = '_remove_format';
      //$form['#action'] = base_path() . drupal_get_path_alias('node/' . $form['#node']->nid);
      //unset($form['author']['_author']);
      break;
  }
}

/**
 * Implements hook_node_presave().
 */
function omitsis_SITEID_node_presave($node) {
  /*switch ($node->type) {
  	case 'article':

      break;
  }*/
}

/**
 * Implements hook_node_insert().
 */
function omitsis_SITEID_node_insert($node) {
  /*switch ($node->type) {
  	case 'article':

     	break;
  }*/
}

/**
 * Implements hook_node_view().
 */
function omitsis_SITEID_node_view($node, $view_mode) {
  // Just make a blog menu item active during viewing blog post detailed page.
  /*$menu_name = 'main-menu';
  if ($view_mode == 'full' && !empty($node->type)){
    switch ($node->type){
      case 'post':
        $path = 'node/5';
        $menu_name = 'menu-secondary-menu';
        break;
      case 'press':
        $path = 'node/59';
        $menu_name = 'menu-secondary-menu';
        break;  
    }
    if (isset($path)) menu_tree_set_path($menu_name, $path);
  }*/
}

/**
 * Implements hook_block_info().
 */
/*function omitsis_SITEID_block_info() {
  $blocks['BLOCK_ID'] = array(
    'info'=> SITE_ID . ': BLOCK TITLE',
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}*/

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function omitsis_SITEID_block_view($delta = '') {
  $block = array();
  switch($delta){
    /*case 'SOME_BLOCK':
      $block['subject'] = '';
      $block['content'] = omitsis_SITEID_render_SOME_BLOCK();
      break;*/
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function omitsis_SITEID_theme($existing, $type, $theme, $path) {
  return array(
    /*'SOME_THEME' => array(
      'variables' => array(),
      'template' => 'theme/SOME_THEME',
    ),*/
  );
}

/*
* Simple Test functions
*/
function omitsis_SITEID_test($type){
  $response = 'No test selected, or test invalid';
  switch ($type){
    case 'SOME_TEST':
      $response = array(
        //'SOME_RESPONSE' => SOME_METHOD_THAT_RETURNS_SOMETHING(),
      );
      break;
  }
  drupal_json_output($response);
  drupal_exit();
}

function _remove_format(&$form){
  unset($form[LANGUAGE_NONE][0]['format']['format']);
  unset($form[LANGUAGE_NONE][0]['format']['guidelines']);
  unset($form[LANGUAGE_NONE][0]['format']['help']);
  return $form;
}
